# Generated by Django 5.0.2 on 2024-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userIdentificationNumber', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
