# Generated by Django 5.0.2 on 2024-02-12 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_alter_notes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userIdentificationNumber',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
