# Generated by Django 5.0.2 on 2024-02-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notes_useridentificationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='your_default@example.com', max_length=255, unique=True),
        ),
    ]
