# Generated by Django 5.0.2 on 2024-02-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_notes_options_notes_useridentificationnumber_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
