version: '3.9'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #   ports:
  #     - '8000:8000'
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '0000:5173'
    volumes:
      - ./frontend:/app

  db:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=notes_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=urvish
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
